name: GitHell

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  abyss_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.10

      - name: Prepare Abyss Directory
        run: mkdir -p abyss

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and Push Changes
        run: |
          git config --global user.name "0x3EF8"
          git config --global user.email "0x3ef8@gmail.com"

          for i in $(seq 1 100); do
            timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            commit_id=$(cat /proc/sys/kernel/random/uuid)

            cat <<EOF > abyss/README.yml
  ________.__  __     ___ ___         .__  .__   
 /  _____/|__|/  |_  /   |   \   ____ |  | |  |  
/   \  ___|  \   __\/    ~    \_/ __ \|  | |  |  
\    \_\  \  ||  |  \    Y    /\  ___/|  |_|  |__
 \______  /__||__|   \___|_  /  \___  >____/____/ 
        \/                 \/       \/            

----------------------------------------------------
Commit ID: $commit_id
Timestamp: $timestamp
Message: If you think youâ€™ve won, think again. HAHAHAHA!
----------------------------------------------------
EOF

            git add abyss/README.yml
            git commit -S -m "If your strategyâ€™s dirty, mineâ€™s worse. ðŸ˜ˆ"
          done

          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
