name: GitHell

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.10

      - name: Abyss
        run: |
          mkdir -p abyss
          echo "ðŸ”¥ You have entered the void. The auto-commits loop forever, consuming all in its path." > abyss/README.yml

      - name: GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and Push 100 Changes
        run: |
          git config user.name "0x3EF8"
          git config user.email "0x3ef8@gmail.com"
          count=0
          while [ $count -lt 100 ]; do
            commit_id=$(cat /proc/sys/kernel/random/uuid)
            echo "ðŸ”¥ You have entered the abyss. Commit ID: $commit_id" > abyss/README.yml
            echo "  ________.__  __     ___ ___         .__  .__   " >> abyss/README.yml
            echo " /  _____/|__|/  |_  /   |   \   ____ |  | |  |  " >> abyss/README.yml
            echo "/   \  ___|  \   __\/    ~    \_/ __ \|  | |  |  " >> abyss/README.yml
            echo "\    \_\  \  ||  |  \    Y    /\  ___/|  |_|  |__" >> abyss/README.yml
            echo " \______  /__||__|   \___|_  /  \___  >____/____/ " >> abyss/README.yml
            echo "        \/                 \/       \/            " >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml
            echo "Commit ID $commit_id - If your strategyâ€™s dirty, mineâ€™s worse. HAHAHAHA!" >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml
            git add abyss/README.yml
            git commit -S -m "ðŸ’€ Auto-Commit from the Abyss: ID $commit_id - If your strategyâ€™s dirty, mineâ€™s worse. HAHAHAHA!"
            count=$((count+1))
          done
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
