name: GitHell

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Create Abyss Directory
        run: mkdir -p abyss

      - name: GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Fetch commit count
        id: commit_count
        run: |
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          past_time=$(date -u -d "-10 minutes" +"%Y-%m-%dT%H:%M:%SZ")
          commit_count=$(git rev-list --count --since="$past_time" --until="$current_time" HEAD)
          echo "commit_count=$commit_count" >> $GITHUB_ENV

      - name: Track Execution
        id: execution_data
        run: |
          execution_count=1
          if [ -f abyss/file1.yml ]; then
            count=$(grep -oP '(?<=Execution Count: )\d+' abyss/file1.yml | tail -1)
            execution_count=$((count + 1))
          fi
          echo "execution_count=$execution_count" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config user.name "0x3EF8"
          git config user.email "0x3ef8@gmail.com"
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          for i in {1..20}; do
            file="abyss/file$i.yml"
            for j in $(seq 1 2000); do
              {
                echo "  ________.__  __     ___ ___         .__  .__   "
                echo " /  _____/|__|/  |_  /   |   \   ____ |  | |  |  "
                echo "/   \  ___|  \   __\/    ~    \_/ __ \|  | |  |  "
                echo "\    \_\  \  ||  |  \    Y    /\  ___/|  |_|  |__"
                echo " \______  /__||__|   \___|_  /  \___  >____/____/ "
                echo "        \/                 \/       \/            "
                echo "----------------------------------------------------"
                echo "The abyss grows deeper with each commit."
                echo "----------------------------------------------------"
                commit_id=$(cat /proc/sys/kernel/random/uuid)
                total_commits=$(git rev-list --count HEAD)
                echo "Commit ID: $commit_id"
                echo "Commit: $total_commits"
                echo "Execution Count: ${{ env.execution_count }}"
                echo "Last Execution Time: $current_time"
                echo "----------------------------------------------------"
              } > "$file"
              git add "$file"
              git commit -S -m "File $i - Commit $j: The abyss deepens. (Total commits: $total_commits, Execution: ${{ env.execution_count }}, Time: $current_time)"
            done
          done
          git push
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
