name: GitHell

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Create Abyss Directory
        run: mkdir -p abyss

      - name: Initialize Execution Data
        run: |
          if [ ! -f abyss/execution_data.txt ]; then
            echo "Execution Count: 0" > abyss/execution_data.txt
          fi

      - name: Configure GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Fetch Commit Count
        id: commit_count
        run: |
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          past_time=$(date -u -d "-5 minutes" +"%Y-%m-%dT%H:%M:%SZ")
          commit_count=$(git rev-list --count --since="$past_time" --until="$current_time" HEAD)
          echo "commit_count=$commit_count" >> $GITHUB_ENV

      - name: Track Execution
        id: execution_data
        run: |
          execution_count=$(grep -oP '(?<=Execution Count: )\d+' abyss/execution_data.txt | tail -1)
          execution_count=$((execution_count + 1))
          echo "execution_count=$execution_count" >> $GITHUB_ENV

      - name: Track Daily Commits
        id: daily_commits
        run: |
          current_date=$(date -u +"%Y-%m-%d")
          if [ -f abyss/daily_commits.txt ]; then
            if grep -q "$current_date" abyss/daily_commits.txt; then
              daily_commit_count=$(grep "$current_date" abyss/daily_commits.txt | awk '{print $5}')
            else
              daily_commit_count=0
            fi
          else
            daily_commit_count=0
          fi
          daily_commit_count=$((daily_commit_count + commit_count))
          echo "daily_commit_count=$daily_commit_count" >> $GITHUB_ENV
          echo "Day ${execution_count} $current_date total commits $daily_commit_count" >> abyss/daily_commits.txt

      - name: Commit and Push Changes
        run: |
          git config user.name "0x3EF8"
          git config user.email "0x3ef8@gmail.com"
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          count=0
          while [ $count -lt 100 ]; do
            echo "  ________.__  __     ___ ___         .__  .__   " > abyss/README.yml
            echo " /  _____/|__|/  |_  /   |   \   ____ |  | |  |  " >> abyss/README.yml
            echo "/   \  ___|  \   __\/    ~    \_/ __ \|  | |  |  " >> abyss/README.yml
            echo "\    \_\  \  ||  |  \    Y    /\  ___/|  |_|  |__" >> abyss/README.yml
            echo " \______  /__||__|   \___|_  /  \___  >____/____/ " >> abyss/README.yml
            echo "        \/                 \/       \/            " >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml
            echo "If you think youâ€™ve won, think again. HAHAHAHA!" >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml
            commit_id=$(cat /proc/sys/kernel/random/uuid)
            total_commits=$(git rev-list --count HEAD)
            echo "Commit ID: $commit_id" >> abyss/README.yml
            echo "Commit: $total_commits" >> abyss/README.yml
            echo "Execution Count: ${{ env.execution_count }}" >> abyss/README.yml
            echo "Last Execution Time: $current_time" >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml
            echo "Total commits today: ${{ env.daily_commit_count }}" >> abyss/README.yml
            echo "Execution Count: ${{ env.execution_count }}" > abyss/execution_data.txt
            echo "Last Execution Time: $current_time" >> abyss/execution_data.txt
            git add abyss/README.yml abyss/execution_data.txt abyss/daily_commits.txt
            git commit -S -m "Auto-Commit: $(date -u +"%Y-%m-%d %H:%M:%S") UTC
            Changes: Updated README with new commit details.
            Total commits: $total_commits
            Execution Count: ${{ env.execution_count }}
            Last Execution Time: $current_time
            Commit ID: $commit_id
            Total commits today: ${{ env.daily_commit_count }}"
            count=$((count+1))
          done
          git push
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
